hoistPattern:
  - '*'
hoistedDependencies:
  /7zip-bin/5.1.1:
    7zip-bin: public
  /@ampproject/remapping/2.2.0:
    '@ampproject/remapping': public
  /@babel/code-frame/7.18.6:
    '@babel/code-frame': public
  /@babel/compat-data/7.20.14:
    '@babel/compat-data': public
  /@babel/core/7.20.12:
    '@babel/core': public
  /@babel/generator/7.20.14:
    '@babel/generator': public
  /@babel/helper-compilation-targets/7.20.7_@babel+core@7.20.12:
    '@babel/helper-compilation-targets': public
  /@babel/helper-environment-visitor/7.18.9:
    '@babel/helper-environment-visitor': public
  /@babel/helper-function-name/7.19.0:
    '@babel/helper-function-name': public
  /@babel/helper-hoist-variables/7.18.6:
    '@babel/helper-hoist-variables': public
  /@babel/helper-module-imports/7.18.6:
    '@babel/helper-module-imports': public
  /@babel/helper-module-transforms/7.20.11:
    '@babel/helper-module-transforms': public
  /@babel/helper-plugin-utils/7.20.2:
    '@babel/helper-plugin-utils': public
  /@babel/helper-simple-access/7.20.2:
    '@babel/helper-simple-access': public
  /@babel/helper-split-export-declaration/7.18.6:
    '@babel/helper-split-export-declaration': public
  /@babel/helper-string-parser/7.19.4:
    '@babel/helper-string-parser': public
  /@babel/helper-validator-identifier/7.19.1:
    '@babel/helper-validator-identifier': public
  /@babel/helper-validator-option/7.18.6:
    '@babel/helper-validator-option': public
  /@babel/helpers/7.20.13:
    '@babel/helpers': public
  /@babel/highlight/7.18.6:
    '@babel/highlight': public
  /@babel/parser/7.20.15:
    '@babel/parser': public
  /@babel/plugin-transform-react-jsx-self/7.18.6_@babel+core@7.20.12:
    '@babel/plugin-transform-react-jsx-self': public
  /@babel/plugin-transform-react-jsx-source/7.19.6_@babel+core@7.20.12:
    '@babel/plugin-transform-react-jsx-source': public
  /@babel/template/7.20.7:
    '@babel/template': public
  /@babel/traverse/7.20.13:
    '@babel/traverse': public
  /@babel/types/7.20.7:
    '@babel/types': public
  /@develar/schema-utils/2.6.5:
    '@develar/schema-utils': public
  /@electron/get/2.0.2:
    '@electron/get': public
  /@electron/universal/1.2.1:
    '@electron/universal': public
  /@esbuild/android-arm/0.17.5:
    '@esbuild/android-arm': public
  /@esbuild/android-arm64/0.17.5:
    '@esbuild/android-arm64': public
  /@esbuild/android-x64/0.17.5:
    '@esbuild/android-x64': public
  /@esbuild/darwin-arm64/0.17.5:
    '@esbuild/darwin-arm64': public
  /@esbuild/darwin-x64/0.17.5:
    '@esbuild/darwin-x64': public
  /@esbuild/freebsd-arm64/0.17.5:
    '@esbuild/freebsd-arm64': public
  /@esbuild/freebsd-x64/0.17.5:
    '@esbuild/freebsd-x64': public
  /@esbuild/linux-arm/0.17.5:
    '@esbuild/linux-arm': public
  /@esbuild/linux-arm64/0.17.5:
    '@esbuild/linux-arm64': public
  /@esbuild/linux-ia32/0.17.5:
    '@esbuild/linux-ia32': public
  /@esbuild/linux-loong64/0.17.5:
    '@esbuild/linux-loong64': public
  /@esbuild/linux-mips64el/0.17.5:
    '@esbuild/linux-mips64el': public
  /@esbuild/linux-ppc64/0.17.5:
    '@esbuild/linux-ppc64': public
  /@esbuild/linux-riscv64/0.17.5:
    '@esbuild/linux-riscv64': public
  /@esbuild/linux-s390x/0.17.5:
    '@esbuild/linux-s390x': public
  /@esbuild/linux-x64/0.17.5:
    '@esbuild/linux-x64': public
  /@esbuild/netbsd-x64/0.17.5:
    '@esbuild/netbsd-x64': public
  /@esbuild/openbsd-x64/0.17.5:
    '@esbuild/openbsd-x64': public
  /@esbuild/sunos-x64/0.17.5:
    '@esbuild/sunos-x64': public
  /@esbuild/win32-arm64/0.17.5:
    '@esbuild/win32-arm64': public
  /@esbuild/win32-ia32/0.17.5:
    '@esbuild/win32-ia32': public
  /@esbuild/win32-x64/0.17.5:
    '@esbuild/win32-x64': public
  /@jridgewell/gen-mapping/0.1.1:
    '@jridgewell/gen-mapping': public
  /@jridgewell/resolve-uri/3.1.0:
    '@jridgewell/resolve-uri': public
  /@jridgewell/set-array/1.1.2:
    '@jridgewell/set-array': public
  /@jridgewell/sourcemap-codec/1.4.14:
    '@jridgewell/sourcemap-codec': public
  /@jridgewell/trace-mapping/0.3.17:
    '@jridgewell/trace-mapping': public
  /@malept/cross-spawn-promise/1.1.1:
    '@malept/cross-spawn-promise': public
  /@malept/flatpak-bundler/0.4.0:
    '@malept/flatpak-bundler': public
  /@nodelib/fs.scandir/2.1.5:
    '@nodelib/fs.scandir': public
  /@nodelib/fs.stat/2.0.5:
    '@nodelib/fs.stat': public
  /@nodelib/fs.walk/1.2.8:
    '@nodelib/fs.walk': public
  /@sindresorhus/is/4.6.0:
    '@sindresorhus/is': public
  /@szmarczak/http-timer/4.0.6:
    '@szmarczak/http-timer': public
  /@tootallnate/once/2.0.0:
    '@tootallnate/once': public
  /@types/cacheable-request/6.0.3:
    '@types/cacheable-request': public
  /@types/debug/4.1.7:
    '@types/debug': public
  /@types/fs-extra/9.0.13:
    '@types/fs-extra': public
  /@types/glob/7.2.0:
    '@types/glob': public
  /@types/http-cache-semantics/4.0.1:
    '@types/http-cache-semantics': public
  /@types/keyv/3.1.4:
    '@types/keyv': public
  /@types/minimatch/5.1.2:
    '@types/minimatch': public
  /@types/ms/0.7.31:
    '@types/ms': public
  /@types/node/18.11.18:
    '@types/node': public
  /@types/prop-types/15.7.5:
    '@types/prop-types': public
  /@types/responselike/1.0.0:
    '@types/responselike': public
  /@types/scheduler/0.16.2:
    '@types/scheduler': public
  /@types/yargs-parser/21.0.0:
    '@types/yargs-parser': public
  /@types/yargs/17.0.22:
    '@types/yargs': public
  /@types/yauzl/2.10.0:
    '@types/yauzl': public
  /agent-base/6.0.2:
    agent-base: public
  /ajv-keywords/3.5.2_ajv@6.12.6:
    ajv-keywords: public
  /ajv/6.12.6:
    ajv: public
  /ansi-regex/5.0.1:
    ansi-regex: public
  /ansi-styles/4.3.0:
    ansi-styles: public
  /anymatch/3.1.3:
    anymatch: public
  /app-builder-bin/4.0.0:
    app-builder-bin: public
  /app-builder-lib/23.6.0:
    app-builder-lib: public
  /argparse/2.0.1:
    argparse: public
  /asar/3.2.0:
    asar: public
  /async-exit-hook/2.0.1:
    async-exit-hook: public
  /async/3.2.4:
    async: public
  /asynckit/0.4.0:
    asynckit: public
  /at-least-node/1.0.0:
    at-least-node: public
  /balanced-match/1.0.2:
    balanced-match: public
  /base64-js/1.5.1:
    base64-js: public
  /binary-extensions/2.2.0:
    binary-extensions: public
  /bluebird-lst/1.0.9:
    bluebird-lst: public
  /bluebird/3.7.2:
    bluebird: public
  /boolean/3.2.0:
    boolean: public
  /brace-expansion/1.1.11:
    brace-expansion: public
  /braces/3.0.2:
    braces: public
  /browserslist/4.21.5:
    browserslist: public
  /buffer-alloc-unsafe/1.1.0:
    buffer-alloc-unsafe: public
  /buffer-alloc/1.2.0:
    buffer-alloc: public
  /buffer-crc32/0.2.13:
    buffer-crc32: public
  /buffer-equal/1.0.0:
    buffer-equal: public
  /buffer-fill/1.0.0:
    buffer-fill: public
  /buffer-from/1.1.2:
    buffer-from: public
  /builder-util-runtime/9.1.1:
    builder-util-runtime: public
  /builder-util/23.6.0:
    builder-util: public
  /cacheable-lookup/5.0.4:
    cacheable-lookup: public
  /cacheable-request/7.0.2:
    cacheable-request: public
  /caniuse-lite/1.0.30001450:
    caniuse-lite: public
  /chalk/4.1.2:
    chalk: public
  /chokidar/3.5.3:
    chokidar: public
  /chownr/2.0.0:
    chownr: public
  /chromium-pickle-js/0.2.0:
    chromium-pickle-js: public
  /ci-info/3.7.1:
    ci-info: public
  /cliui/8.0.1:
    cliui: public
  /clone-response/1.0.3:
    clone-response: public
  /color-convert/2.0.1:
    color-convert: public
  /color-name/1.1.4:
    color-name: public
  /colors/1.0.3:
    colors: public
  /combined-stream/1.0.8:
    combined-stream: public
  /commander/5.1.0:
    commander: public
  /compare-version/0.1.2:
    compare-version: public
  /concat-map/0.0.1:
    concat-map: public
  /convert-source-map/1.9.0:
    convert-source-map: public
  /cross-spawn/7.0.3:
    cross-spawn: public
  /csstype/3.1.1:
    csstype: public
  /debug/4.3.4:
    debug: public
  /decompress-response/6.0.0:
    decompress-response: public
  /defer-to-connect/2.0.1:
    defer-to-connect: public
  /define-properties/1.1.4:
    define-properties: public
  /delayed-stream/1.0.0:
    delayed-stream: public
  /detect-node/2.1.0:
    detect-node: public
  /dir-compare/2.4.0:
    dir-compare: public
  /dmg-builder/23.6.0:
    dmg-builder: public
  /dmg-license/1.0.11:
    dmg-license: public
  /dotenv-expand/5.1.0:
    dotenv-expand: public
  /dotenv/9.0.2:
    dotenv: public
  /ejs/3.1.8:
    ejs: public
  /electron-osx-sign/0.6.0:
    electron-osx-sign: public
  /electron-publish/23.6.0:
    electron-publish: public
  /electron-to-chromium/1.4.285:
    electron-to-chromium: public
  /emoji-regex/8.0.0:
    emoji-regex: public
  /end-of-stream/1.4.4:
    end-of-stream: public
  /env-paths/2.2.1:
    env-paths: public
  /es6-error/4.1.1:
    es6-error: public
  /escalade/3.1.1:
    escalade: public
  /escape-string-regexp/4.0.0:
    escape-string-regexp: public
  /extract-zip/2.0.1:
    extract-zip: public
  /fast-deep-equal/3.1.3:
    fast-deep-equal: public
  /fast-glob/3.2.12:
    fast-glob: public
  /fast-json-stable-stringify/2.1.0:
    fast-json-stable-stringify: public
  /fastq/1.15.0:
    fastq: public
  /fd-slicer/1.1.0:
    fd-slicer: public
  /filelist/1.0.4:
    filelist: public
  /fill-range/7.0.1:
    fill-range: public
  /form-data/4.0.0:
    form-data: public
  /fs-extra/10.1.0:
    fs-extra: public
  /fs-minipass/2.1.0:
    fs-minipass: public
  /fs.realpath/1.0.0:
    fs.realpath: public
  /fsevents/2.3.2:
    fsevents: public
  /function-bind/1.1.1:
    function-bind: public
  /gensync/1.0.0-beta.2:
    gensync: public
  /get-caller-file/2.0.5:
    get-caller-file: public
  /get-intrinsic/1.2.0:
    get-intrinsic: public
  /get-stream/5.2.0:
    get-stream: public
  /glob-parent/5.1.2:
    glob-parent: public
  /glob/7.2.3:
    glob: public
  /global-agent/3.0.0:
    global-agent: public
  /globals/11.12.0:
    globals: public
  /globalthis/1.0.3:
    globalthis: public
  /got/11.8.6:
    got: public
  /graceful-fs/4.2.10:
    graceful-fs: public
  /graceful-readlink/1.0.1:
    graceful-readlink: public
  /has-flag/4.0.0:
    has-flag: public
  /has-property-descriptors/1.0.0:
    has-property-descriptors: public
  /has-symbols/1.0.3:
    has-symbols: public
  /has/1.0.3:
    has: public
  /hosted-git-info/4.1.0:
    hosted-git-info: public
  /http-cache-semantics/4.1.1:
    http-cache-semantics: public
  /http-proxy-agent/5.0.0:
    http-proxy-agent: public
  /http2-wrapper/1.0.3:
    http2-wrapper: public
  /https-proxy-agent/5.0.1:
    https-proxy-agent: public
  /iconv-lite/0.6.3:
    iconv-lite: public
  /immutable/4.2.3:
    immutable: public
  /inflight/1.0.6:
    inflight: public
  /inherits/2.0.4:
    inherits: public
  /is-binary-path/2.1.0:
    is-binary-path: public
  /is-ci/3.0.1:
    is-ci: public
  /is-core-module/2.11.0:
    is-core-module: public
  /is-extglob/2.1.1:
    is-extglob: public
  /is-fullwidth-code-point/3.0.0:
    is-fullwidth-code-point: public
  /is-glob/4.0.3:
    is-glob: public
  /is-number/7.0.0:
    is-number: public
  /isbinaryfile/4.0.10:
    isbinaryfile: public
  /isexe/2.0.0:
    isexe: public
  /jake/10.8.5:
    jake: public
  /js-tokens/4.0.0:
    js-tokens: public
  /js-yaml/4.1.0:
    js-yaml: public
  /jsesc/2.5.2:
    jsesc: public
  /json-buffer/3.0.1:
    json-buffer: public
  /json-schema-traverse/0.4.1:
    json-schema-traverse: public
  /json-stringify-safe/5.0.1:
    json-stringify-safe: public
  /json5/2.2.3:
    json5: public
  /jsonfile/6.1.0:
    jsonfile: public
  /keyv/4.5.2:
    keyv: public
  /lazy-val/1.0.5:
    lazy-val: public
  /lib-esm/0.3.0:
    lib-esm: public
  /lodash/4.17.21:
    lodash: public
  /loose-envify/1.4.0:
    loose-envify: public
  /lowercase-keys/2.0.0:
    lowercase-keys: public
  /lru-cache/5.1.1:
    lru-cache: public
  /magic-string/0.27.0:
    magic-string: public
  /matcher/3.0.0:
    matcher: public
  /merge2/1.4.1:
    merge2: public
  /micromatch/4.0.5:
    micromatch: public
  /mime-db/1.52.0:
    mime-db: public
  /mime-types/2.1.35:
    mime-types: public
  /mime/2.6.0:
    mime: public
  /mimic-response/3.1.0:
    mimic-response: public
  /minimatch/3.1.2:
    minimatch: public
  /minimist/1.2.7:
    minimist: public
  /minipass/4.0.1:
    minipass: public
  /minizlib/2.1.2:
    minizlib: public
  /mkdirp/1.0.4:
    mkdirp: public
  /ms/2.1.2:
    ms: public
  /nanoid/3.3.4:
    nanoid: public
  /node-releases/2.0.9:
    node-releases: public
  /normalize-path/3.0.0:
    normalize-path: public
  /normalize-url/6.1.0:
    normalize-url: public
  /notbundle/0.3.4:
    notbundle: public
  /object-keys/1.1.1:
    object-keys: public
  /once/1.4.0:
    once: public
  /p-cancelable/2.1.1:
    p-cancelable: public
  /path-is-absolute/1.0.1:
    path-is-absolute: public
  /path-key/3.1.1:
    path-key: public
  /path-parse/1.0.7:
    path-parse: public
  /pend/1.2.0:
    pend: public
  /picocolors/1.0.0:
    picocolors: public
  /picomatch/2.3.1:
    picomatch: public
  /playwright-core/1.30.0:
    playwright-core: public
  /plist/3.0.6:
    plist: public
  /postcss/8.4.21:
    postcss: public
  /progress/2.0.3:
    progress: public
  /pump/3.0.0:
    pump: public
  /punycode/2.3.0:
    punycode: public
  /queue-microtask/1.2.3:
    queue-microtask: public
  /quick-lru/5.1.1:
    quick-lru: public
  /react-refresh/0.14.0:
    react-refresh: public
  /read-config-file/6.2.0:
    read-config-file: public
  /readdirp/3.6.0:
    readdirp: public
  /require-directory/2.1.1:
    require-directory: public
  /resolve-alpn/1.2.1:
    resolve-alpn: public
  /resolve/1.22.1:
    resolve: public
  /responselike/2.0.1:
    responselike: public
  /reusify/1.0.4:
    reusify: public
  /rimraf/3.0.2:
    rimraf: public
  /roarr/2.15.4:
    roarr: public
  /rollup/3.13.0:
    rollup: public
  /run-parallel/1.2.0:
    run-parallel: public
  /safer-buffer/2.1.2:
    safer-buffer: public
  /sanitize-filename/1.6.3:
    sanitize-filename: public
  /sax/1.2.4:
    sax: public
  /scheduler/0.23.0:
    scheduler: public
  /semver-compare/1.0.0:
    semver-compare: public
  /semver/6.3.0:
    semver: public
  /serialize-error/7.0.1:
    serialize-error: public
  /shebang-command/2.0.0:
    shebang-command: public
  /shebang-regex/3.0.0:
    shebang-regex: public
  /simple-update-notifier/1.1.0:
    simple-update-notifier: public
  /source-map-js/1.0.2:
    source-map-js: public
  /source-map-support/0.5.21:
    source-map-support: public
  /source-map/0.6.1:
    source-map: public
  /sprintf-js/1.1.2:
    sprintf-js: public
  /stat-mode/1.0.0:
    stat-mode: public
  /string-width/4.2.3:
    string-width: public
  /strip-ansi/6.0.1:
    strip-ansi: public
  /sumchecker/3.0.1:
    sumchecker: public
  /supports-color/7.2.0:
    supports-color: public
  /supports-preserve-symlinks-flag/1.0.0:
    supports-preserve-symlinks-flag: public
  /tar/6.1.13:
    tar: public
  /temp-file/3.4.0:
    temp-file: public
  /tmp-promise/3.0.3:
    tmp-promise: public
  /tmp/0.2.1:
    tmp: public
  /to-fast-properties/2.0.0:
    to-fast-properties: public
  /to-regex-range/5.0.1:
    to-regex-range: public
  /truncate-utf8-bytes/1.0.2:
    truncate-utf8-bytes: public
  /type-fest/0.13.1:
    type-fest: public
  /universalify/2.0.0:
    universalify: public
  /update-browserslist-db/1.0.10_browserslist@4.21.5:
    update-browserslist-db: public
  /uri-js/4.4.1:
    uri-js: public
  /utf8-byte-length/1.0.4:
    utf8-byte-length: public
  /vite-plugin-electron/0.11.1:
    vite-plugin-electron: public
  /which/2.0.2:
    which: public
  /wrap-ansi/7.0.0:
    wrap-ansi: public
  /wrappy/1.0.2:
    wrappy: public
  /xmlbuilder/15.1.1:
    xmlbuilder: public
  /y18n/5.0.8:
    y18n: public
  /yallist/4.0.0:
    yallist: public
  /yargs-parser/21.1.1:
    yargs-parser: public
  /yargs/17.6.2:
    yargs: public
  /yauzl/2.10.0:
    yauzl: public
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@7.18.1
pendingBuilds: []
prunedAt: Fri, 03 Feb 2023 14:34:48 GMT
publicHoistPattern:
  - '*'
registries:
  default: https://registry.npmjs.org/
skipped:
  - /@esbuild/android-arm/0.16.17
  - /@esbuild/android-arm/0.17.5
  - /@esbuild/android-arm64/0.16.17
  - /@esbuild/android-arm64/0.17.5
  - /@esbuild/android-x64/0.16.17
  - /@esbuild/android-x64/0.17.5
  - /@esbuild/darwin-arm64/0.16.17
  - /@esbuild/darwin-arm64/0.17.5
  - /@esbuild/darwin-x64/0.16.17
  - /@esbuild/darwin-x64/0.17.5
  - /@esbuild/freebsd-arm64/0.16.17
  - /@esbuild/freebsd-arm64/0.17.5
  - /@esbuild/freebsd-x64/0.16.17
  - /@esbuild/freebsd-x64/0.17.5
  - /@esbuild/linux-arm/0.16.17
  - /@esbuild/linux-arm/0.17.5
  - /@esbuild/linux-arm64/0.16.17
  - /@esbuild/linux-arm64/0.17.5
  - /@esbuild/linux-ia32/0.16.17
  - /@esbuild/linux-ia32/0.17.5
  - /@esbuild/linux-loong64/0.16.17
  - /@esbuild/linux-loong64/0.17.5
  - /@esbuild/linux-mips64el/0.16.17
  - /@esbuild/linux-mips64el/0.17.5
  - /@esbuild/linux-ppc64/0.16.17
  - /@esbuild/linux-ppc64/0.17.5
  - /@esbuild/linux-riscv64/0.16.17
  - /@esbuild/linux-riscv64/0.17.5
  - /@esbuild/linux-s390x/0.16.17
  - /@esbuild/linux-s390x/0.17.5
  - /@esbuild/netbsd-x64/0.16.17
  - /@esbuild/netbsd-x64/0.17.5
  - /@esbuild/openbsd-x64/0.16.17
  - /@esbuild/openbsd-x64/0.17.5
  - /@esbuild/sunos-x64/0.16.17
  - /@esbuild/sunos-x64/0.17.5
  - /@esbuild/win32-arm64/0.16.17
  - /@esbuild/win32-arm64/0.17.5
  - /@esbuild/win32-ia32/0.16.17
  - /@esbuild/win32-ia32/0.17.5
  - /@esbuild/win32-x64/0.16.17
  - /@esbuild/win32-x64/0.17.5
  - /@types/plist/3.0.2
  - /@types/verror/1.10.6
  - /assert-plus/1.0.0
  - /astral-regex/2.0.0
  - /buffer/5.7.1
  - /cli-truncate/2.1.0
  - /core-util-is/1.0.2
  - /crc/3.8.0
  - /dmg-license/1.0.11
  - /extsprintf/1.4.1
  - /fsevents/2.3.2
  - /iconv-corefoundation/1.1.7
  - /ieee754/1.2.1
  - /node-addon-api/1.7.2
  - /slice-ansi/3.0.0
  - /smart-buffer/4.2.0
  - /verror/1.10.1
storeDir: /home/manan/.local/share/pnpm/store/v3
virtualStoreDir: .pnpm
