name: install_dependencies

on: [push]

jobs:
  tidy:
    name: Go ${{ matrix.go }} Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          go-version: ${{ matrix.node }}
      - run: npm build 
